### ISSUE TITLE
What should I do to generate Level-0 maps randomly？

### ISSUE THREAD

**Issue by nianba** [efc-robot/Explore-Bench#7]

**Comment by FarawaySail** [comment]
As mentioned in the paper, the complex scenes are obtained by combining the basic scenes (loop, corridor, corner, and room). Since these basic scenarios are based on specific templates, they can be well pre-defined in the Level-0, and some basic scene generation processes can be designed to generate more scenes randomly and automatically. For example, we can first put a random number of rooms on a fixed size open space, then generate some corridors between the rooms, and finally put some random corners.
